apiVersion: v1
kind: PersistentVolume
metadata:
  name: identity-db-persistent-volume
spec:
  capacity:
    storage: {{ .Values.identity_db.persistentVolume.capacity.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.identity_db.persistentVolume.hostPath.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-db-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.identity_db.persistentVolumeClaim.resources.requests.storage }}

