apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-db
spec:
  selector:
    matchLabels:
      app: identity-db
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
        - name: identity-db
          image: mysql:8.0.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: IDENTITY_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: USER_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: identity-db-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: identity-db-persistent-storage
          persistentVolumeClaim:
            claimName: identity-db-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: identity-db
spec:
  ports:
    - port: 3306
  selector:
    app: identity-db
