apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: ttkien2402/shipping-service
        ports:
        - containerPort: 8086
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: SHIPPING_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: USER_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  type: ClusterIP
  selector:
    app: shipping-service
  ports:
    - port: 8086
      targetPort: 8086
